# This AppSpec file is now configured to work with AWS Systems Manager
# to securely retrieve your Docker Hub credentials.
version: 0.0
os: linux

# The `files` section tells CodeDeploy which files to copy to your server.
files:
  - source: docker-compose.yml
    destination: /var/www/reactapp
  - source: scripts
    destination: /var/www/reactapp/scripts

# The `hooks` section defines the actions to take at each stage of the deployment.
hooks:
  BeforeInstall:
    - location: scripts/stop_pm2.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    # This hook now runs a modified script that fetches the credentials securely.
    - location: scripts/start_docker.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 60
      runas: ec2-user
