version: 0.0
os: linux

files:
  - source: docker-compose.yml
    destination: /var/www/reactapp
  - source: scripts
    destination: /var/www/reactapp/scripts

hooks:
  BeforeInstall:
    - location: scripts/stop_pm2.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_docker.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 60
      runas: ec2-user