version: 0.0
os: linux

# Copy the React production files onto the instance
files:
  - source: build/
    destination: /var/www/reactapp

hooks:
  BeforeInstall:
    - location: scripts/stop_pm2.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_pm2.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 60
      runas: ec2-user
