version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm ci
  build:
    commands:
      - echo "Building React app"
      - npm run build
  post_build:
    commands:
      - echo "Preparing deployable artifact"
      - mkdir -p dist
      - cp -r build dist/build
      - cp appspec.yml dist/
      - mkdir -p dist/scripts
      - cp -r scripts/* dist/scripts/
      - chmod +x dist/scripts/*.sh
artifacts:
  files:
    - '**/*'
  base-directory: dist
